### ISSUE TITLE
All endpoints return 400

### ISSUE THREAD

**Issue by Meemaw** [Unleash/unleash-edge#144]
### Describe the bug

Trying `unleash-edge` out locally (running via docker) and observing 400s on pretty much any type of request I do. The body is empty so this is completely un-actionable.

Trying endpoints like `http://localhost:3063/api/proxy/all` and including the `Authorization` header.

Was trying to migrate from unleash-proxy, but missing a concrete migration guide. The edge doesn't seem to be 1:1 compatible with proxy (different API endpoints etc...).

### Subscription type

None

### Hosting type

None

**Comment by chriswk** [comment]
Hi @Meemaw 

We do need to come up with a migration guide from the proxy, that is on us.

I'm going to try to help you a bit further:

Since you're getting HTTP Status Code 400, I'm guessing you're trying to use old proxy keys to access Edge, and you started edge in Edge mode? When started in Edge mode, you will need to create proper client keys using Unleash's admin panel.
https://docs.getunleash.io/reference/api-tokens-and-client-keys

Edge will return 400 (Bad Data) if it can't parse the token being used in the authorization header following the `<project>:<environment>.<secret>` format.

If you're using the proxy sdk, you'll need a Frontend token, but you'll also give Edge a client token that is allowed to read the features you're trying to evaluate. See https://docs.getunleash.io/reference/unleash-edge#edge and particularly the paragraph about frontend tokens.

**Comment by Meemaw** [comment]
Hi @chriswk thanks for the reply.

Is a migration guide in the works/planned? In that case I would wait for that so I don't have to nag you for any issue we'll hit 🙂

**Comment by chriswk** [comment]
Yes it is in the works. I've added a issue to this repo as well to be more transparent on what we're doing.
