### ISSUE TITLE
Filter /api/client/features by tag query parameter

### ISSUE THREAD

**Issue by Ampa1R** [Unleash/unleash-edge#601]
### Describe the feature request

I would like to request support for the `tag` query parameter in the `/api/client/features` endpoint for Unleash Edge

### Background

Currently, the `tag` parameter is supported by Unleash but this functionality is not yet available in Unleash Edge

I saw a previous issue with fix for `namePrefix ` #149 and it was mentioned:
>Edge can't support filtering by tags, since that is not data we get from Unleash (it's not part of the client features contract), and Edge does not have access to the database

Despite mentioned issue adding support for the tag parameter would help bring consistency between the Unleash API and Edge API providing a seamless experience for users

Additionally i can't find mentions in the docs saying that the Edge API could work differently from the Unleash API. If there are other differences it would be really helpful to include these in the docs and create a list of unsupported features to assist users in understanding the limitations of the Edge

### Solution suggestions

Possible solutions could be extending current API or create different endpoint that includes tags information

If these options couldn't be implemented in nearest future it would be great to note this details in docs

**Comment by gastonfournier** [comment]
Hi @Ampa1R, I think the best in this case is to add a note into documentation saying that this feature is not available in Edge. Filtering by tag is not even documented in our OpenAPI spec as we expect feature filtering should happen because of the API key you use that's bound to a project and environment. 

Having filtering by tag inside unleash server adds additional complexity and probably should not be there in the first place. But changing that would be a breaking change. We'll continue discussing this internally but meanwhile I'll open a PR noting down this disparity between edge and unleash server
